name: Rahman CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indiriliyor
        uses: actions/checkout@v4

      - name: Dosyaları Listele
        run: ls -la

      - name: index.html Kontrolü
        run: cat index.html

      - name: Workflow başarıyla tamamlandı
        run: echo "CI Pipeline başarıyla çalıştı."
